### ISSUE TITLE
android 统计页面路径无效

### ISSUE THREAD

**Issue by sunny20131314** [esseak/rn-umeng#25]
① MobclickAgent.onPageStart(currentRouter.name);  这个调用无效（umeng统计仍然只有 activity, why???）
②  MobclickAgent.onEvent('aaa');  这么调用时报错如下

 说是需要3个参数，但我看文档， 也可以传一个参数？

报错如下
com.facebook.react.bridge.NativeArgumentsParseException: Umeng.onEvent got 1 arguments, expected 3 at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:291) at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158) at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) at android.os.Handler.handleCallback(Handler.java:743) at android.os.Handler.dispatchMessage(Handler.java:95) at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31) at android.os.Looper.loop(Looper.java:150) at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196) at java.lang.Thread.run(Thread.java:833)

**Comment by sunny20131314** [comment]
②  MobclickAgent.onEvent('aaa');  已经解决了，是前端调用的问题

**Comment by sunny20131314** [comment]
MobclickAgent.openActivityDurationTrack(false) 禁止默认的页面统计方式，这样将不会再自动统计Activity。

在activity 中加入该代码，umeng文档里说得很清楚，没有细看... T_T
